### ISSUE TITLE
Cheapest hours

### ISSUE THREAD

**Issue by iiseppi** [msegzda/homebridge-nordpool-baltics#15]
Hi,

First, BIG thanks to you for making this plugin!! 

Is there possibility to make one switch which is Nordpool_cheapest12Hours?? Or even better, make Nordpool_cheapestXXHours, where you can specify to XX to something between 1-23 hours?.

What I want to do is, run floor heating every day cheapest 12 hours without noticing what is the price for electricity.

**Comment by msegzda** [comment]
Will implement an extension of Nordpool_cheapest[4-8]Hours on the next release. Thanks for the suggestion!

**Comment by msegzda** [comment]
This is now implemented with latest v1.4.1 release. Enjoy!
