### ISSUE TITLE
Homebridge version 2.0

### ISSUE THREAD

**Issue by iiseppi** [msegzda/homebridge-nordpool-baltics#17]
Hi,

Homebridge is getting ready for version 2.0 and there is some breaking changes coming.
Have you had time to think and check your awesome plugin to get worked in version 2.0?

Here is some info for version 2.0:
https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

**Comment by msegzda** [comment]
Thank you, again, for reaching out. I added support for Homebridge v2
(beta). Will ship in next hours
